version: '3.5'

services:
  chrome-vpn:
    image: ericdraken/chrome-vpn:armv7
    cap_add:
      - NET_ADMIN # Needed for VPN tunnel adapter
    ports:
      - "${CHROME_RDP_PORT:-3000}:3000"
      - "${PROXY_PORT:-3001}:3001"
    expose:
      - 8080 # Actuator port
    dns:
      - "${DNS_SERVER_1:-9.9.9.9}"
      - "${DNS_SERVER_2:-1.1.1.1}"
    volumes:
      - ./conf/chromium.sh:/app/chromium/chromium.sh:ro
      - ./conf/privoxy.conf:/etc/services.d/privoxy/config:ro
      - /dev/shm:/dev/shm # Use shared memory with the host
      - ./usedvpns:/usedvpns
      - ./ovpn:/ovpn
    tmpfs:
      - /tmp
    env_file:
      - ./env/chrome-vpn.env
      - ./env/password.env