version: '3'

networks:
  proxynet:
    driver: bridge

services:
  chrome-haproxy:
    build:
      context: haproxy
    networks:
      - proxynet
    ports:
      - "${CHROME_RDP_PORT:-3000}:3000"
    restart: unless-stopped
    depends_on:
      - chrome-vpn1
      - chrome-vpn2
    environment:
      FRONTEND_PORT: 3000
      BACKENDS_PORT: 3000
      BACKENDS: "chrome-vpn1 chrome-vpn2"
      HTTPCHK: "HEAD /health"
      HTTPCHKPORT: 8080

  proxy-haproxy:
    build:
      context: haproxy
    networks:
      - proxynet
    ports:
      - "${PROXY_PORT:-3001}:3001"
    restart: unless-stopped
    depends_on:
      - chrome-vpn1
      - chrome-vpn2
    environment:
      FRONTEND_PORT: 3001
      BACKENDS_PORT: 3001
      BACKENDS: "chrome-vpn1 chrome-vpn2"
      HTTPCHK: "HEAD /health"
      HTTPCHKPORT: 8080

  chrome-vpn1: &chrome-vpn
    image: ericdraken/chrome-vpn:armv7
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # Needed for VPN tunnel adapter
    networks:
      - proxynet
    expose:
      - 3000 # Chrome Debug Protocol port
      - 3001 # Chrome bypass port
      - 8080 # Actuator port
    dns:
      - "${DNS_SERVER_1:-9.9.9.9}"
      - "${DNS_SERVER_2:-1.1.1.1}"
    volumes:
      - ./.chromium.sh:/app/chromium/chromium.sh:ro
      - /dev/shm:/dev/shm # Use shared memory with the host
      - ./usedvpns:/usedvpns
    tmpfs:
      - /tmp
    env_file:
      - ./env/chrome-vpn.env
      - ./env/password.env
    environment:
      MAX_CONCURRENT_SESSIONS: 3

  chrome-vpn2:
    <<: *chrome-vpn

  echo:
    build:
      context: echo
    restart: unless-stopped
    networks:
      - proxynet
    expose:
      - 8080