#!/usr/bin/with-contenv bash

base_dir="/vpn"
auth_file="$base_dir/auth"
config_file="$base_dir/config.ovpn"

exec openvpn --cd "$base_dir" --config "$config_file" --auth-user-pass "$auth_file" --auth-nocache ${OPENVPN_OPTS}
