#!/usr/bin/with-contenv bash

echo "Firewall everything has to go through the vpn"
iptables  -F OUTPUT
ip6tables -F OUTPUT 2> /dev/null
iptables  -P OUTPUT DROP
ip6tables -P OUTPUT DROP 2> /dev/null
iptables  -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT 2> /dev/null
iptables  -A OUTPUT -o lo -j ACCEPT
ip6tables -A OUTPUT -o lo -j ACCEPT 2> /dev/null
iptables  -A OUTPUT -o tap0 -j ACCEPT
ip6tables -A OUTPUT -o tap0 -j ACCEPT 2>/dev/null
iptables  -A OUTPUT -o tun0 -j ACCEPT
ip6tables -A OUTPUT -o tun0 -j ACCEPT 2> /dev/null
iptables  -A OUTPUT -d `ip -o addr show dev eth0 | awk '$3 == "inet" {print $4}'` -j ACCEPT
ip6tables -A OUTPUT -d `ip -o addr show dev eth0 | awk '$3 == "inet6" {print $4}'` -j ACCEPT 2> /dev/null
iptables  -A OUTPUT -p udp --dport 53 -j ACCEPT
ip6tables -A OUTPUT -p udp --dport 53 -j ACCEPT 2> /dev/null
iptables  -A OUTPUT -p tcp -m owner --gid-owner vpn -j ACCEPT 2>/dev/null &&
iptables  -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT || {
    # iptables  -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT
    iptables  -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT; }
ip6tables -A OUTPUT -p tcp -m owner --gid-owner vpn -j ACCEPT 2>/dev/null &&
ip6tables -A OUTPUT -p udp -m owner --gid-owner vpn -j ACCEPT 2>/dev/null || {
    # ip6tables -A OUTPUT -p tcp -m tcp --dport 443 -j ACCEPT 2>/dev/null
    ip6tables -A OUTPUT -p udp -m udp --dport 1194 -j ACCEPT 2>/dev/null; }

echo "Bypass requests to NordVPN through regular connection"
iptables  -A OUTPUT -o eth0 -d `echo $URL_NORDVPN_API | awk -F/ '{print $3}'` -j ACCEPT
ip6tables -A OUTPUT -o eth0 -d `echo $URL_NORDVPN_API | awk -F/ '{print $3}'` -j ACCEPT 2> /dev/null

iptables  -A OUTPUT -o eth0 -d `echo $URL_OVPN_FILES | awk -F/ '{print $3}'` -j ACCEPT
ip6tables -A OUTPUT -o eth0 -d `echo $URL_OVPN_FILES | awk -F/ '{print $3}'` -j ACCEPT 2> /dev/null

echo "Keep track of connection requests"
iptables -A INPUT -i eth0 -p tcp --tcp-flags SYN SYN -j LOG --log-prefix "Connection request: "
ip6tables -A INPUT -i eth0 -p tcp --tcp-flags SYN SYN -j LOG --log-prefix "Connection request: " 2> /dev/null

exit 0
