#!/usr/bin/with-contenv bash

ovpn_dir="/ovpn"

if [ `ls -A $ovpn_dir | wc -l` -eq 0 ]
then
    echo "Server configs not found. Download configs from NordVPN"
    curl -s $URL_OVPN_FILES -o /tmp/ovpn.zip
    unzip -q /tmp/ovpn.zip -d /tmp/ovpn
    mv /tmp/ovpn/*/*.ovpn $ovpn_dir
    rm -rf /tmp/*
fi

exit 0
