#!/usr/bin/with-contenv bash
set -e

cp /app/squid/squid-defaults.conf /squid/etc/squid.conf

mkdir -p ${SQUID_LOG_DIR}
chmod -R 755 ${SQUID_LOG_DIR}
chown -R ${SQUID_USER}:${SQUID_USER} ${SQUID_LOG_DIR}

mkdir -p ${SQUID_CACHE_DIR}
chown -R ${SQUID_USER}:${SQUID_USER} ${SQUID_CACHE_DIR}

# Confirm the configs are good
/squid/sbin/squid -k parse || exit 1

# REF: https://elatov.github.io/2019/01/using-squid-to-proxy-ssl-sites/
mkdir /squid/certs
openssl req -new -newkey rsa:2048 \
  -sha256 -days 365 -nodes -x509 \
  -extensions v3_ca \
  -subj '/CN=client' \
  -keyout /squid/certs/squid-ca-key.pem \
  -out /squid/certs/squid-ca-cert.pem

cat /squid/certs/squid-ca-cert.pem /squid/certs/squid-ca-key.pem \
  > /squid/certs/squid-ca-cert-key.pem

chown -R ${SQUID_USER}:${SQUID_USER} /squid/certs

# Create cache folders
exec /squid/sbin/squid -N -C -z -d 1 || exit 1

exit 0