#!/usr/bin/with-contenv bash

if [[ -z "$AUTH_FILE" ]]; then
  echo "Auth file location missing. Exiting."
  exit 1
fi

if [[ -z "$VPN_USER" || -z "$VPN_PASS" ]]; then
  echo "VPN user or password is empty. Exiting."
  exit 1
fi

# Create auth_file
echo "$VPN_USER" > $AUTH_FILE
echo "$VPN_PASS" >> $AUTH_FILE
chmod 0600 $auth_file
exit 0